apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
        - name: app-html-container
          image: registry.gitlab.com/argocd7062629/app-html
          ports:
            - containerPort: 80